import { BASE_CSS, BASE_HTML, BASE_JS, DETAIL_LAYOUT_JS, MOBILE_FILTER_CSS } from "./review-assets-base.js";
import { DERIVED_VIEW_CSS, PROVENANCE_CSS, PROVENANCE_JS } from "./review-assets-provenance.js";
import { PACKET_REVIEW_CSS, PACKET_REVIEW_JS } from "./review-assets-packet.js";
import {
  HISTORY_EMPTY_JS,
  REPORT_INTEGRITY_JS,
  REPORT_SIGNATURE_JS,
  STACK_REPORT_CSS,
  STACK_REPORT_JS,
} from "./review-assets-stack.js";
import {
  ACCEPTANCE_CSS,
  ACCEPTANCE_JS,
  ARCHIVE_CSS,
  ARCHIVE_JS,
  COVERAGE_CSS,
  COVERAGE_DESKTOP_FIT_CSS,
  COVERAGE_JS,
  UPGRADE_CSS,
  UPGRADE_JS,
} from "./review-assets-release.js";
import { TRANSITION_HISTORY_CSS, TRANSITION_HISTORY_JS } from "./review-assets-transition-history.js";
import { LINEAGE_CONTINUITY_CSS, LINEAGE_CONTINUITY_JS } from "./review-assets-lineage-continuity.js";

export const REVIEW_STYLE_ASSETS = [
  BASE_CSS,
  MOBILE_FILTER_CSS,
  PROVENANCE_CSS,
  DERIVED_VIEW_CSS,
  PACKET_REVIEW_CSS,
  STACK_REPORT_CSS,
  ARCHIVE_CSS,
  UPGRADE_CSS,
  COVERAGE_CSS,
  COVERAGE_DESKTOP_FIT_CSS,
  ACCEPTANCE_CSS,
  TRANSITION_HISTORY_CSS,
  LINEAGE_CONTINUITY_CSS,
] as const;

export const REVIEW_SCRIPT_ASSETS = [
  BASE_JS,
  DETAIL_LAYOUT_JS,
  PROVENANCE_JS,
  STACK_REPORT_JS,
  HISTORY_EMPTY_JS,
  REPORT_INTEGRITY_JS,
  REPORT_SIGNATURE_JS,
  ARCHIVE_JS,
  UPGRADE_JS,
  COVERAGE_JS,
  ACCEPTANCE_JS,
  TRANSITION_HISTORY_JS,
  LINEAGE_CONTINUITY_JS,
  PACKET_REVIEW_JS,
] as const;

export const REVIEW_HTML = BASE_HTML;
export const REVIEW_STYLES = REVIEW_STYLE_ASSETS.join("");
export const REVIEW_JAVASCRIPT = REVIEW_SCRIPT_ASSETS.join("");
