export const STACK_REPORT_CSS = `.stack-report{display:grid;grid-template-columns:minmax(220px,1fr) auto;gap:14px 18px;background:#163f31;color:#fff;border-radius:16px;padding:16px 19px;margin-bottom:14px}.stack-report strong{display:block;font-size:15px}.stack-report p{margin:5px 0 0;color:#cde2d8;font-size:12px}.stack-revisions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.stack-revisions span{background:rgba(255,255,255,.1);border-radius:999px;padding:7px 10px;font:11px/1.2 ui-monospace,SFMono-Regular,monospace}.stack-revisions .dirty{background:#7f3d22}.stack-diff{grid-column:1/-1;color:#cde2d8;font-size:11px}.stack-diff b{color:#fff}.stack-history{grid-column:1/-1;display:flex;flex-wrap:wrap;gap:7px;border-top:1px solid rgba(255,255,255,.16);padding-top:11px}.stack-history button{border:1px solid transparent;border-radius:8px;background:transparent;color:#cde2d8;padding:5px 7px;font-size:11px}.stack-history button[aria-current=true]{border-color:rgba(255,255,255,.4);background:rgba(255,255,255,.1);color:#fff;font-weight:700}@media(max-width:760px){.stack-report{grid-template-columns:1fr}.stack-revisions{justify-content:flex-start}.stack-history,.stack-diff{grid-column:1}}`;

export const STACK_REPORT_JS = `(async()=>{const data=(await bootstrap).stackHistory;if(!data)return;const keys=[['evidenceForge','Evidence'],['agentBlackBox','Agent'],['solLedger','Ledger']],section=el('section','stack-report');section.setAttribute('aria-label','統合検証履歴');const summary=el('div'),revisions=el('div','stack-revisions'),diff=el('div','stack-diff'),history=el('div','stack-history');section.append(summary,revisions,diff,history);function renderRun(index){const report=data.reports[index],previous=data.reports[index+1];summary.replaceChildren(el('strong','','✓ 3製品の統合検証に成功'));const changed=previous?keys.filter(([key])=>report.revisions[key].commit!==previous.revisions[key].commit).length:0;summary.append(el('p','',report.eventCount+'件を改ざん検査済み・履歴 '+data.reports.length+'件'+(previous?'・前回から'+changed+'製品更新':'')));revisions.replaceChildren();for(const [key,label]of keys){const state=report.revisions[key];revisions.append(el('span',state.clean?'':'dirty',label+' '+state.commit.slice(0,7)+(state.clean?'':' 変更あり')))}diff.replaceChildren();if(previous){const parts=keys.map(([key,label])=>label+' '+(report.revisions[key].commit===previous.revisions[key].commit?'変更なし':previous.revisions[key].commit.slice(0,7)+' → '+report.revisions[key].commit.slice(0,7)));diff.append(el('b','','前回との差分: '),document.createTextNode(parts.join('・')))}history.querySelectorAll('button').forEach((button,i)=>button.setAttribute('aria-current',String(i===index)))}data.reports.slice(0,8).forEach((item,index)=>{const date=item.recordedAt?new Date(item.recordedAt).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'日時なし',button=el('button','',date+' · '+item.trustedHeadSha256.slice(0,7));button.type='button';button.onclick=()=>renderRun(index);history.append(button)});renderRun(0);document.querySelector('.metrics').after(section)})().catch(()=>{});`;

export const HISTORY_EMPTY_JS = `document.addEventListener('click',e=>{const target=e.target;if(!(target instanceof Element)||!target.closest('.stack-history button'))return;const diff=document.querySelector('.stack-diff');if(diff&&!diff.textContent)diff.textContent='最初の記録（比較対象なし）'});`;

export const REPORT_INTEGRITY_JS = `(async()=>{const data=(await bootstrap).stackHistory;if(!data)return;if(!data.reports[0]?.integrity)return;const apply=()=>{const summary=document.querySelector('.stack-report p');if(!summary||summary.dataset.integrity)return false;summary.append(document.createTextNode('・レポート整合性確認済み'));summary.dataset.integrity='verified';return true};apply()})().catch(()=>{});`;

export const REPORT_SIGNATURE_JS = `(async()=>{const data=(await bootstrap).stackHistory;if(!data)return;const report=data.reports[0],signature=report?.signature,rotation=report?.trustRotation;if(!signature)return;const apply=()=>{const summary=document.querySelector('.stack-report p');if(!summary||summary.dataset.signature)return false;const expiry=signature.validUntil?'・信頼期限 '+new Date(signature.validUntil).toLocaleDateString('ja-JP'):'',rotationText=!rotation?'':rotation.completedRotations?'・鍵交代 '+rotation.completedRotations+'回確認済み':'・鍵履歴確認済み',scheduled=rotation?.scheduledCount?'・次の鍵交代 '+rotation.scheduledCount+'件予定':'';summary.append(document.createTextNode('・署名者 '+signature.verifiedKeyIds.length+'/'+signature.threshold+'名確認済み'+expiry+rotationText+scheduled));summary.dataset.signature='verified';return true};apply()})().catch(()=>{});`;
